"""revisi tabel semua user

Revision ID: 1399bec79b3b
Revises: 
Create Date: 2026-05-26 04:24:10.464464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1399bec79b3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layanan',
    sa.Column('id_layanan', sa.String(), nullable=False),
    sa.Column('nama_layanan', sa.String(), nullable=True),
    sa.Column('tipe_output', sa.String(), nullable=True),
    sa.Column('unit_penanggung_jawab', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_layanan')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nama_lengkap', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('tanggal_terdaftar', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('admin_sistem',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nip', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('audit_logs',
    sa.Column('id_log', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('waktu', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_aktor', sa.String(), nullable=True),
    sa.Column('role_aktor', sa.String(), nullable=True),
    sa.Column('aksi', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['email_aktor'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_index(op.f('ix_audit_logs_email_aktor'), 'audit_logs', ['email_aktor'], unique=False)
    op.create_table('mahasiswa',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nim', sa.String(), nullable=True),
    sa.Column('program_studi', sa.String(), nullable=True),
    sa.Column('departemen', sa.String(), nullable=True),
    sa.Column('fakultas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('nim')
    )
    op.create_table('staff_akademik',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nip', sa.String(), nullable=True),
    sa.Column('unit_kerja', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('chatbot_sessions',
    sa.Column('id_chat', sa.String(), nullable=False),
    sa.Column('email_mahasiswa', sa.String(), nullable=True),
    sa.Column('pesan_user', sa.String(), nullable=True),
    sa.Column('jawaban_bot', sa.Text(), nullable=True),
    sa.Column('waktu_kirim', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['email_mahasiswa'], ['mahasiswa.email'], ),
    sa.PrimaryKeyConstraint('id_chat')
    )
    op.create_index(op.f('ix_chatbot_sessions_email_mahasiswa'), 'chatbot_sessions', ['email_mahasiswa'], unique=False)
    op.create_table('knowledge_base',
    sa.Column('id_kb', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('judul', sa.String(), nullable=True),
    sa.Column('kategori', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('waktu_upload', sa.DateTime(), nullable=True),
    sa.Column('diupload_oleh', sa.String(), nullable=True),
    sa.Column('waktu_setujui', sa.DateTime(), nullable=True),
    sa.Column('disetujui_oleh', sa.String(), nullable=True),
    sa.Column('waktu_tolak', sa.DateTime(), nullable=True),
    sa.Column('ditolak_oleh', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['disetujui_oleh'], ['admin_sistem.email'], ),
    sa.ForeignKeyConstraint(['ditolak_oleh'], ['admin_sistem.email'], ),
    sa.ForeignKeyConstraint(['diupload_oleh'], ['staff_akademik.email'], ),
    sa.PrimaryKeyConstraint('id_kb')
    )
    op.create_index(op.f('ix_knowledge_base_id_kb'), 'knowledge_base', ['id_kb'], unique=False)
    op.create_index(op.f('ix_knowledge_base_judul'), 'knowledge_base', ['judul'], unique=False)
    op.create_table('tiket_layanan',
    sa.Column('id_tiket', sa.String(), nullable=False),
    sa.Column('waktu_submit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('subjek', sa.String(), nullable=True),
    sa.Column('kategori', sa.String(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('data_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_lampiran', sa.String(), nullable=True),
    sa.Column('email_mahasiswa', sa.String(), nullable=True),
    sa.Column('email_staff', sa.String(), nullable=True),
    sa.Column('id_layanan', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['email_mahasiswa'], ['mahasiswa.email'], ),
    sa.ForeignKeyConstraint(['email_staff'], ['staff_akademik.email'], ),
    sa.ForeignKeyConstraint(['id_layanan'], ['layanan.id_layanan'], ),
    sa.PrimaryKeyConstraint('id_tiket')
    )
    op.create_index(op.f('ix_tiket_layanan_email_mahasiswa'), 'tiket_layanan', ['email_mahasiswa'], unique=False)
    op.create_table('notifikasi',
    sa.Column('id_notifikasi', sa.String(), nullable=False),
    sa.Column('pesan', sa.String(), nullable=True),
    sa.Column('waktu', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('id_tiket', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_tiket'], ['tiket_layanan.id_tiket'], ),
    sa.PrimaryKeyConstraint('id_notifikasi')
    )
    op.create_index(op.f('ix_notifikasi_id_tiket'), 'notifikasi', ['id_tiket'], unique=False)
    op.create_table('tanggapan_staff',
    sa.Column('id_tanggapan', sa.String(), nullable=False),
    sa.Column('id_tiket', sa.String(), nullable=True),
    sa.Column('email_staff', sa.String(), nullable=True),
    sa.Column('pesan', sa.Text(), nullable=False),
    sa.Column('file_output', sa.String(), nullable=True),
    sa.Column('waktu', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['email_staff'], ['staff_akademik.email'], ),
    sa.ForeignKeyConstraint(['id_tiket'], ['tiket_layanan.id_tiket'], ),
    sa.PrimaryKeyConstraint('id_tanggapan'),
    sa.UniqueConstraint('id_tiket')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tanggapan_staff')
    op.drop_index(op.f('ix_notifikasi_id_tiket'), table_name='notifikasi')
    op.drop_table('notifikasi')
    op.drop_index(op.f('ix_tiket_layanan_email_mahasiswa'), table_name='tiket_layanan')
    op.drop_table('tiket_layanan')
    op.drop_index(op.f('ix_knowledge_base_judul'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_id_kb'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    op.drop_index(op.f('ix_chatbot_sessions_email_mahasiswa'), table_name='chatbot_sessions')
    op.drop_table('chatbot_sessions')
    op.drop_table('staff_akademik')
    op.drop_table('mahasiswa')
    op.drop_index(op.f('ix_audit_logs_email_aktor'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('admin_sistem')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('layanan')
    # ### end Alembic commands ###
