"""hapus id_keyword di chatbot_sessions

Revision ID: 176859b74bb0
Revises: 
Create Date: 2026-05-25 19:52:24.049867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '176859b74bb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'waktu',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_logs_email_aktor'), 'audit_logs', ['email_aktor'], unique=False)
    op.alter_column('chatbot_sessions', 'waktu_kirim',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_chatbot_sessions_email_mahasiswa'), 'chatbot_sessions', ['email_mahasiswa'], unique=False)
    op.drop_constraint(op.f('chatbot_sessions_id_keyword_terdeteksi_fkey'), 'chatbot_sessions', type_='foreignkey')
    op.drop_column('chatbot_sessions', 'id_keyword_terdeteksi')
    op.alter_column('notifikasi', 'waktu',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_notifikasi_id_tiket'), 'notifikasi', ['id_tiket'], unique=False)
    op.alter_column('tanggapan_staff', 'waktu',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tiket_layanan', 'waktu_submit',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tiket_layanan', 'data_request',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_tiket_layanan_email_mahasiswa'), 'tiket_layanan', ['email_mahasiswa'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_tiket_layanan_email_mahasiswa'), table_name='tiket_layanan')
    op.alter_column('tiket_layanan', 'data_request',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tiket_layanan', 'waktu_submit',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tanggapan_staff', 'waktu',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_notifikasi_id_tiket'), table_name='notifikasi')
    op.alter_column('notifikasi', 'waktu',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('chatbot_sessions', sa.Column('id_keyword_terdeteksi', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chatbot_sessions_id_keyword_terdeteksi_fkey'), 'chatbot_sessions', 'knowledge_base', ['id_keyword_terdeteksi'], ['id_keyword'])
    op.drop_index(op.f('ix_chatbot_sessions_email_mahasiswa'), table_name='chatbot_sessions')
    op.alter_column('chatbot_sessions', 'waktu_kirim',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_logs_email_aktor'), table_name='audit_logs')
    op.alter_column('audit_logs', 'waktu',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
