"""tambah hash_lampiran tanggapan

Revision ID: 47a674c62ef9
Revises: 69f2734509d1
Create Date: 2026-06-01 06:06:28.589179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a674c62ef9'
down_revision: Union[str, Sequence[str], None] = '69f2734509d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tanggapan_staff', sa.Column('hash_lampiran', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tanggapan_staff', 'hash_lampiran')
    # ### end Alembic commands ###
