"""drop semester from mahasiswa

Revision ID: 5a8ab041b865
Revises: 47a674c62ef9
Create Date: 2026-06-03 02:30:36.912613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8ab041b865'
down_revision: Union[str, Sequence[str], None] = '47a674c62ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahasiswa', sa.Column('alamat', sa.String(length=255), nullable=True))
    op.drop_column('mahasiswa', 'semester')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahasiswa', sa.Column('semester', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('mahasiswa', 'alamat')
    # ### end Alembic commands ###
