"""tambah kolom nim dan prodi pengaju

Revision ID: 69f2734509d1
Revises: f643b0ead691
Create Date: 2026-05-30 18:39:11.111764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f2734509d1'
down_revision: Union[str, Sequence[str], None] = 'f643b0ead691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahasiswa', sa.Column('semester', sa.String(), nullable=True))
    op.add_column('tiket_layanan', sa.Column('nim_pengaju', sa.String(), nullable=True))
    op.add_column('tiket_layanan', sa.Column('program_studi_pengaju', sa.String(), nullable=True))
    op.alter_column('tiket_layanan', 'subjek',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tiket_layanan', 'kategori',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_tiket_layanan_nim_pengaju'), 'tiket_layanan', ['nim_pengaju'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tiket_layanan_nim_pengaju'), table_name='tiket_layanan')
    op.alter_column('tiket_layanan', 'kategori',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tiket_layanan', 'subjek',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tiket_layanan', 'program_studi_pengaju')
    op.drop_column('tiket_layanan', 'nim_pengaju')
    op.drop_column('mahasiswa', 'semester')
    # ### end Alembic commands ###
