"""remove foreign key from audit_logs

Revision ID: 7705c82ea351
Revises: fd73d14b3a0b
Create Date: 2026-05-28 13:25:36.934982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7705c82ea351'
down_revision: Union[str, Sequence[str], None] = 'fd73d14b3a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_logs_email_aktor_fkey'), 'audit_logs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('audit_logs_email_aktor_fkey'), 'audit_logs', 'users', ['email_aktor'], ['email'])
    # ### end Alembic commands ###
