"""remove foreign key from audit_logs

Revision ID: b86ef5cccf6f
Revises: 7705c82ea351
Create Date: 2026-05-28 13:31:00.603884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86ef5cccf6f'
down_revision: Union[str, Sequence[str], None] = '7705c82ea351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
