"""tambah public key staff

Revision ID: dbd138c476b6
Revises: 1399bec79b3b
Create Date: 2026-05-26 05:10:01.456425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd138c476b6'
down_revision: Union[str, Sequence[str], None] = '1399bec79b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_akademik', sa.Column('public_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_akademik', 'public_key')
    # ### end Alembic commands ###
