"""tambah wadah signature di tanggapan staff

Revision ID: e7805906acf0
Revises: dbd138c476b6
Create Date: 2026-05-26 05:58:19.290075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7805906acf0'
down_revision: Union[str, Sequence[str], None] = 'dbd138c476b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tanggapan_staff', sa.Column('digital_signature', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tanggapan_staff', 'digital_signature')
    # ### end Alembic commands ###
