"""tambah kolom encrypted_private_key

Revision ID: fd73d14b3a0b
Revises: e7805906acf0
Create Date: 2026-05-28 06:12:01.726815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd73d14b3a0b'
down_revision: Union[str, Sequence[str], None] = 'e7805906acf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_akademik', sa.Column('encrypted_private_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_akademik', 'encrypted_private_key')
    # ### end Alembic commands ###
